### ISSUE TITLE
require() not supported

### ISSUE THREAD

**Issue by BevanR** [brunocodutra/flow-bin-loader#1]
flow-bin-loader fails on the first require() in the entry point.

**Comment by brunocodutra** [comment]
Thanks for reporting. 

I don't seem to be able to reproduce the issue, could you share the contents of your `.flowconfig` file?

Meanwhile a wild guess, did you setup [`module.name_mapper=`](https://flowtype.org/docs/advanced-configuration.html#options) in the `[options]` section of `.flowconfig` to inject paths relative to `<PROJECT_ROOT>`? 

I.e., something like 

```
module.name_mapper='^\(.*\)$' -> '<PROJECT_ROOT>/src/\1'
```

where `<PROJECT_ROOT>` expands to the directory where `.flowconfig` lives.

**Comment by BevanR** [comment]
- `/` webpack command runs from here
  - `.flowconfig`
  - `dist/`
    - ...
  - `tests/`
    - ...
  - `node_modules/`
    - ...
  - `ui/`
    - `Mything.js`
    - `main.js` (webpack entrypoint)
    - `includes/`
      - `styles.scss`
      - `MyClass.js`
      - ...

### `.flowconfig`

```
[ignore]
    .*/dist/.*
    .*/node_modules/.*

[options]
    unsafe.enable_getters_and_setters=true
    module.name_mapper.extension='scss' -> 'empty/object'
```

## Notes

- `'empty/object'` refers to https://www.npmjs.com/package/empty
- `require('./MyThing')` in `main.js` is what fails:

```
bevan@bevanslaptop:~/my-project
> webpack
/Users/bevan/my-project/ui/main.js:2
  2: window.MyApp = require('./MyThing')
                    ^^^^^^^^^^^^^^^^^^^^ ./MyThing. Required module not found


Found 1 error

Hash: e7c9d293612c65905d18
Version: webpack 1.13.3
Time: 2251ms
    + 1 hidden modules

ERROR in ./ui/main.js
Module build failed:

**Comment by brunocodutra** [comment]
Thanks for the details.

When checking files individually flow expects paths to be resolved with respect to the directory where `.flowconfig` lives, so you actually need to tell flow how to map paths to the correct directory using the  [`module.name_mapper`](https://flowtype.org/docs/advanced-configuration.html#options) option.

In short, simply add the following line to the `[options]` section of your `.flowconfig`

```
module.name_mapper='^\(.*\)$' -> '<PROJECT_ROOT>/ui/\1'
```

**Comment by brunocodutra** [comment]
Since this configuration might not be obvious at first, I added detailed instructions to the README file #2

**Comment by brunocodutra** [comment]
@BevanR did it fix it for you?

**Comment by BevanR** [comment]
If I recall correctly, it helped understand the issue, but didn't resolve it.  I switched to a different loader, then switched away from Flow completely to TypeScript, which has much better tooling, especially for JetBrains IDEs, partly because of https://youtrack.jetbrains.com/issue/WEB-24344
